### PR TITLE
Honor the 'expires_in' value returned with the OAUTH token.

### PR DESCRIPTION
**Pull request by diranged**
OAUTH Tokens are returned with an 'expires_in' value (7200s by default).
After that, the token expires. Honor this value by tracking it on every
call to the self.client attr and re-freshing the client OAUTH token when
we hit the expiration time.

Also: Includes a bunch of pep8 style guide fixes.

### CODE REVIEW

**Comment by fr33jc** [comment]
@diranged - thanks for the contribution!  Could you please separate the timestamp functionality into a separate patch from the PEP8-ish hunks?

Regarding these style changes (and we can elaborate further in a separate pull request), from what I can tell your changes are mostly about *line continuations*.  I ([and others](https://github.com/jcrocholl/pep8/issues/167)) find the `pep8` tool oversteps in this area.  If you look at the actual text of PEP8 -> https://www.python.org/dev/peps/pep-0008/#indentation you will find that even the examples allow for variation in the actual number of spaces used for indenting line continuations.

In addition, the thinking behind keeping the closing paren on its own line for line continuations in the existing python-rightscale code is to allow convenient and consistent addition/removal/commenting of the continued sequence.  I.e. starting with:

```python
some_value = some_func(
        elem1,
        elem2,
        elem3,
        )
```

You can have a very focused patch that removes `elem3` without affecting the closing paren.

**Comment by diranged** [comment]
@fr33jc, you're right ... I should have left the Pep8 changes to a separate change. I've stripped them out and force-committed a new version that just has the Token code.

**Comment by diranged** [comment]
Let me know if you can merge this code... unfortunately because `setup.py` sucks, our https://github.com/Nextdoor/kingpin code cannot be installed via PyPI without the python-rightscale library being pushd to PyPI as well.

(pip installs via github work fine .. but thats not very reliable)

**Comment by fr33jc** [comment]
@diranged - pypi has been updated with the 0.1.3 release of python-rightscale.  The only functional change is your ``expires_in`` code.

**Pull request merged**
