### PR TITLE
Move the login() logic into HTTPClient.

### PR DESCRIPTION
**Pull request by diranged**
By moving the login() logic into the HTTPClient object, we can keep
track of the Oauth token expiration time there too. This means that the
HTTPClient() object is self sufficient after its been instantiated, and
can always handle re-authing as necessary.

This fixes a bug where you could create a RightScale.Resource() object
with a supplied HTTPClient() object, wait 2 hours, and have the oauth
token expire.

@brantai, @siminm: What do you two think of this approach? Its more code than I wanted to touch, but it seems to be the more correct way to deal with managing the login credentials to me.

### CODE REVIEW

**Comment by brantai** [comment]
Sorry for the long wait on a reply, neither @fr33jc or I have access to a rightscale account to test this with anymore.  I'm going to go ahead & merge this, & if you'd like to be added as a contributor so you don't have to do the pull-request dance let me know.  If @fr33jc is fine with it, I'd just assume transfer ownership of the project to you if you're actively maintaining it.

**Comment by fr33jc** [comment]
@brantai - fine with me.

**Comment by diranged** [comment]
@brantai,
  Sorry for the long delay here -- but we're back again and hacking at this module .. I keep hoping that one day I'll just write a fresh client in Tornado and against RightScale 1.6 API, but I'm not going to get to it. I have a few more changes to make to the module. I would be happy to have the ownership transferred over to the Nextdoor organization (https://github.com/Nextdoor) -- but ideally you can also transfer the PyPI ownership to us so that we can do "real" releases as we tweak the code?

**Comment by brantai** [comment]
Sure thing.  What's the user on pypi I should transfer it to?

**Comment by brantai** [comment]
Also, github won't let me transfer directly to Nextdoor & I couldn't transfer to you because you already have a fork.  I've added you as a contributor for now.  Once again, let me know what email you'd like pypi ownership transferred to.

**Comment by mikhail** [comment]
@brantai thanks for doing this! If you add either one of us to Admin permission we'll be able to transfer this to Nextdoor's namespace. The pypi user is simply `nextdoor`

Thanks again!

**Pull request merged**
